title: PDF Compression Add-On
description: Give this Add-On a public link to a Google Drive or Dropbox file or folder, it will try to download and compress each PDF before uploading to DocumentCloud. 
type: object
documents:
  []
properties:
  url:
    title: URL
    type: string
    format: uri
    description: A publicly accessible Google Drive or Dropbox folder or file. 
required:
  - url
